### ISSUE TITLE
Ajout de la reconnaissance de flags

### ISSUE THREAD

**Issue by philippetrepanier** [FrankZappaLevasseur/gif3000-compilateur-assembleur#2]
Je propose l'ajout d'un drapeau de la mise à jour des flags (flags write) par la lettre « F » 

Par exemple, on pourrait avoir l'instruction **SUBF R0, R2**.

Par le fait même je crois pertinent d'encapsuler les insctructions dans une classe **Instructions** avec les méthodes suivantes:
- Constructeur : accepte l'opcode en hex sous string ou en ASCII string. Cela pour permettre la conversion dans les deux sens.
- Méthode __str__ : permettre la conversion de l'instruction en forme lisible humainement donc texte ASCII.
- Méthode __hex__ : permet la conversion en hexadécimal de l'instruction par un cast.

Je suis ouvert à tous commentaires.

**Comment by franklevasseur** [comment]
Désolé pour le délai!

Oui c'est une bonne idée, j'avais pensé faire quelque chose du genre pour dire d'updater les flags. Peut-être quelque chose comme ça sinon:

SUB R0, R2 -f

T'en penses quoi?

J'ai aussi fait un refactor qui ressemble à ce que tu proposes; J'ai fait une classe Instruction qui encapsule toute les méthodes pour compiler une seule instruction et une classe Program qui est composé d'une collection d'instructions. Le refactor va faciliter l'ajout de features.

**Comment by franklevasseur** [comment]
Voilà, c'est ajouté
